### PR TITLE
B | Layer Deletion Bug Fix

### PR DESCRIPTION
**Pull request by emplam27**
레이어 삭제 기능 버그 잡았습니다.

### CODE REVIEW

**Review by Wu22e — APPROVED** [review]
VERY GOOD

**Review by yusokk — APPROVED** [review]
I'm not sure but, it seems that addresses of activeLayer and newLayer might be different, although they are pointing the same layer object. So indexOf method cannot find the index. LGTM.

**Review by Jeongmin94 — COMMENTED** [review]
good

**Review by Jeongmin94 — APPROVED** [review]
Good

**Review by 2014100890 — COMMENTED** [review]
o...okay

**Review by 2014100890 — APPROVED** [review]
ㅇㅇㅇ

**Pull request merged**
