### PR TITLE
U, C | Refactor directories and Create room -list, entrance, live-roo…

### PR DESCRIPTION
**Pull request by yusokk**
U, C | Refactor directories and Create room -list, entrance, live-room components(REST-API)

### CODE REVIEW

**Review by 2014100890 — APPROVED** [review]
It looks nice !

**Review by Jeongmin94 — APPROVED** [review]
teach me react

**Review by emplam27 — APPROVED** [review]
LGTM

**Review by Wu22e — APPROVED** [review]
LG

**Pull request merged**
