### PR TITLE
Feature/saving room info

### PR DESCRIPTION
**Pull request by yusokk**

### CODE REVIEW

**Review by Jeongmin94 — APPROVED** [review]
GOOD

**Review by Wu22e — APPROVED** [review]
good

**Review by emplam27 — APPROVED** [review]
goooooooooooooooooood

**Review by 2014100890 — APPROVED** [review]
<구현사항>
1. / (get) : return room list
2. /room (post) : create drawing room 
3. /room/room-uuid (post) : join room (add room member)
4. /room/entrance (post) : return member list in the room

**Pull request merged**
